eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

jwt.key=Z3V2ZW5saWJpcmJhc2U2NHNlY3JldGtleWZvcmp3dHNlY3VyaXR5MTIzNDU2Nzg5MA==
